### ISSUE TITLE
Follow 3000 people

### ISSUE THREAD

**Issue by Myloune** [timgrossmann/InstaPy#1283]
Hello I can go back or how to follow the people who follow this user he follow by default 10 user.
I wish to modify it and also it stops without reaching the name that I defined in amout

configuration  : 
session.follow_user_followers(['user1', 'user2], amount=3000, randomize=False, sleep_delay=30)

**Comment by converge** [comment]
It's a good idea to avoid this kind of behavior, it's acting like a spam machine.
