### ISSUE TITLE
Follow users followers - bugged with new update

### ISSUE THREAD

**Issue by cainky** [timgrossmann/InstaPy#3180]
## Expected Behavior
Follow a users followers without following the "suggested" users that pop up

## Current Behavior
Pulls wrong users

## Possible Solution (optional)
Don't pull "suggested users" when they appear - as these users are related to who your account follows

**Comment by txaiwieser** [comment]
I have the same problem here, the list suggested-users is being used to follow :/

**Comment by cainky** [comment]
Still broken? Has anyone tested?

**Comment by andreescocard** [comment]
Your problem shows "Grabbed 0 usernames"?
Same here

**Comment by Yaxit** [comment]
I experienced the same issue, which is quite dangerous actually.
I'm not following, but interacting with some user's followers, but the interactions actually happens with my suggested ones.
Anyone can confirm that this has been solved in the update?

**Comment by Tachenz** [comment]
I can confirm that it is not sold. just followed people from suggested :)

**Comment by JonathandelaSen** [comment]
Still happening. I ended up commenting stuff like "Like it!" to suggested people that I do not follow but I know and they know me. Embarrasing.

**Comment by 46960** [comment]
Having the same issue! Is anyone working on it?  :(
