### ISSUE TITLE
Crashes right after opening

### ISSUE THREAD

**Issue by rubsonalok2** [timgrossmann/InstaPy#469]
The program breaks after I open the program gives the error following

```
action = ActionChains(browser).move_to_element(inputs[0]).click().send_keys(username) 
IndexError: list index out of range
```

I can not open the robbery anymore, my boss is going to fire me if it stops like this

Was working yesterday and today but today stopped working all thefts do not work anymore nor open right
I really need them working right away so my customers are satisfy and they do not cut the service

**Comment by rubsonalok2** [comment]
I do not function much the github in my current knowledge I want a quick tidy that does not work

**Comment by BernardoGO** [comment]
The commit d7af29d in #457 fixes this issue.
