### ISSUE TITLE
Illegal Instruction  - Raspberry Pi Zero W

### ISSUE THREAD

**Issue by rsnotes** [timgrossmann/InstaPy#4741]
## Expected Behavior
in shell:
```
$ python3
>>> import instapy
>>>
```

## Current Behavior
```
$ python3
>>> import instapy
Illegal instruction
$
```
even importing instapy doesn't work. There is no traceback or anything other than "illegal instruction"

## InstaPy configuration
- a Raspberry Pi Zero W running Raspbian Lite
- followed the guide [here](https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md) for chrome exactly
- chromedriver works:
```
$ chromedriver 
Starting ChromeDriver 72.0.3626.121 on port 9515
```
- chromium installed (not sure if it works though - maybe different issue)
```
$ chromium-browser --headless
[0731/021642.392190:ERROR:browser_main_loop.cc(670)] Failed to put Xlib into threaded mode.
[0731/021642.563022:ERROR:gpu_process_transport_factory.cc(1029)] Lost UI shared context.
Fontconfig warning: "/etc/fonts/fonts.conf", line 160: blank doesn't take any effect anymore. please remove it from your fonts.conf
[0731/021644.349455:ERROR:viz_main_impl.cc(197)] Exiting GPU process due to errors during initialization
$
```

**Comment by sfgabe** [comment]
Same Illegal Instruction error here, running on Raspberry Pi Zero. Same results for "chromedriver" and "chromium-browser --headless" as @rsnotes too.

**Comment by gerfra** [comment]
!!!! Same Illegal Instruction error

**Comment by gerfra** [comment]
I found the solution to this error, the program "ChromeDriver and Geckodriver" is compiled for a 64bit architecture!!! And Pizero and my board is a Armv6..... 32bit!!! I don't want to spend money to run a simple script, I'll try to compile it. 
To verify your status, just use this command "**getconf LONG_BIT**"
