### ISSUE TITLE
like_by_tag on raspberry creates error

### ISSUE THREAD

**Issue by thursd4y** [timgrossmann/InstaPy#5861]
## Description
I have a script that's automatically run each day by a cronjob on a raspberry pi. 
First it follows between 100-150 people who follow seceted accounts. (Which works fine.)
And then starts to interact with users based on tags. 
Which will result in the following error quite fast.

Does somebody know how to fix this?
## Error
INFO [2020-10-31 11:39:50] [instauser]  Finished following 1 users' `Followers`! xD

INFO [2020-10-31 11:39:50] [instauser]  Followed: 105
INFO [2020-10-31 11:39:50] [instauser]  Already followed: 0
INFO [2020-10-31 11:39:50] [instauser]  Not valid users: 19
INFO [2020-10-31 11:39:50] [instauser]  Tag [1/3]
INFO [2020-10-31 11:39:50] [instauser]  --> b'congo'
INFO [2020-10-31 11:40:02] [instauser]  desired amount: 45  |  top posts [disabled]: 9  |  possible posts: 1553308
INFO [2020-10-31 11:40:24] [instauser]  Like# [1/45]
INFO [2020-10-31 11:40:24] [instauser]  https://www.instagram.com/p/CHATyOBAjP_/
INFO [2020-10-31 11:40:30] [instauser]  Image from: b'veller_onlinetz'
INFO [2020-10-31 11:40:30] [instauser]  Link: b'https://www.instagram.com/p/CHATyOBAjP_/'
INFO [2020-10-31 11:40:30] [instauser]  Description: b'#veller_onlinetz(high quality)\xf0\x9f\x92\xaf\xf0\x9f\x92\xaf Guarantee \xf0\x9f\x91\x89price#30,000 Tzsh #14$ #denimjeans\xf0\x9f\x91\x96\xf0\x9f\x91\x96\xf0\x9f\x91\x8cbest\n\xf0\x9f\x91\x89we sell\xe2\x9c\x85julma/wholesalers \xf0\x9f\x93\x8c\xf0\x9f\x93\x8c\nWhtspp No #+255789099212 \xf0\x9f\x91\x89All size 30,31,32,33,34,36( depend on)\xf0\x9f\x91\x89 collars \xe2\x9c\x85\xe2\x9c\x85\n.\n.\n.\nTz\xf0\x9f\x87\xb9\xf0\x9f\x87\xbf delivery for Dar 5000/10000 Tzsh (Various depending on the delivery distance)country wide\n.\n.\n.\n.\n#veller_onlinetz#kigali#moshi#nairobian#millardayoupdates#bizmalawi#mwanamchiupdates#dodoma#kinshasa#Malawian#azamtv#cloudstv#musoma#lubumbashi#mwanamboka#voiceofcongo#congo#congles#congolais#brazzaville#igerskenya#igersnairobi#nairobikenya#nairobian#'
INFO [2020-10-31 11:40:30] [instauser]  Location: b'Kenya,nairobi'
INFO [2020-10-31 11:40:30] [instauser]  Not liked this post! ~less likes exist off minumum limit at 1
INFO [2020-10-31 11:40:30] [instauser]  --> Image not liked: b'None'
INFO [2020-10-31 11:40:30] [instauser]  Like# [2/45]
INFO [2020-10-31 11:40:30] [instauser]  https://www.instagram.com/p/CHATrXmAt0k/
INFO [2020-10-31 11:40:40] [instauser]  Sessional Live Report:
	|> LIKED 0 images  |  ALREADY LIKED: 0
	|> COMMENTED on 0 images
	|> FOLLOWED 105 users  |  ALREADY FOLLOWED: 0
	|> UNFOLLOWED 0 users
	|> LIKED 0 comments
	|> REPLIED to 0 comments
	|> INAPPROPRIATE images: 0
	|> NOT VALID users: 19
	|> WATCHED 0 story(ies)  |  WATCHED 0 reel(s)

[Session lasted 2.17 hours]
INFO [2020-10-31 11:40:40] [instauser]  Session ended!
Traceback (most recent call last):
  File "/home/pi/plantphant/simple.py", line 88, in <module>
    amount=random.randint(30, 50), interact=True)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 1935, in like_by_tags
    self.logger,
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/like_util.py", line 621, in check_link
    user_name,
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: window.insta_data is undefined

## Script
This is the script I use:

~~~ 
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True)


with smart_run(session):
    
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=6000,
                                    max_following=3000,
                                    min_followers=30,
                                    min_following=30)


    session.set_action_delays(enabled=True, like=5.2, randomize=True, random_range_from=70, random_range_to=140)
    session.set_action_delays(enabled=True, like=6.3, randomize=True, random_range_from=70, random_range_to=140)

    session.set_delimit_liking(enabled=True, max_likes=150, min_likes=4)
    session.set_delimit_commenting(enabled=True, max_comments=4, min_comments=0)

    session.set_skip_users(skip_private=False,
                       skip_no_profile_pic=True,
                       no_profile_pic_percentage=100)
    session.set_simulation(enabled=True, percentage=66)

    
    amount_number = random.randint(90,160)
    session.follow_user_followers(random.sample(['plantatreeco', 'impact', 'greenpeace', 'natgeotravel', 'earthpix'], 1),
                                  amount=amount_number, randomize=False,
                                  interact=False, sleep_delay=240)


    session.set_user_interact(amount=random.randint(1,2), randomize=True, percentage=70,
                              media='Photo')

    session.set_do_like(enabled=True, percentage=90)
    session.set_do_comment(enabled=True, percentage=5)
    session.set_do_follow(enabled=False)
    session.set_comments(["Some amazing comment phrases"],
                         media='Photo')

    session.like_by_tags(random.sample(like_tag_list, 3),
                         amount=random.randint(30, 50), interact=True)
    """ Joining Engagement Pods...
    """
    session.join_pods(topic='entertainment', engagement_mode='no_comments')

**Comment by neiram44** [comment]
I got what look like a very similar issue #5852 but have not found how to fix it so far...
