### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by anpusheshop** [timgrossmann/InstaPy#98]
my steps:
pip install . | (successful)
quickstart.py - changed username and password 
and then I launched the program - google chrome with instagram lon in page opened
and this error occured:
`quickstart.py", line 11, in <module>
    InstaPy(username=os.getenv('my_username'), password=os.getenv('my_psw'))\
/InstaPy-master 2/instapy/instapy.py", line 68, in login
    if not login_user(self.browser, self.username, self.password):
InstaPy-master 2/instapy/login_util.py", line 19, in login_user
    username_elem.send_keys(username)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 320, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT, {'value': keys_to_typing(value)})
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/common/utils.py", line 150, in keys_to_typing
    for i in range(len(val)):
TypeError: object of type 'NoneType' has no len()`

Thanks for help :)

**Comment by foname** [comment]
Have you ever tried ?
`
export my_username="<Your username>"
export my_psw="<Your password>"
`

**Comment by anpusheshop** [comment]
I set my acc info in the file quickstart.py. I have to set them in cmd?

**Comment by foname** [comment]
You can try to export your variables in cmd, and then run the script.

**Comment by anpusheshop** [comment]
It doesnt help :/ Thanks anyway, any other suggestion : )

**Comment by foname** [comment]
Are you still getting the same error?
You could check your env from your console
`printenv my_username`
`printenv my_psw`
If you export it correctly, it'll print out your values.

**Comment by anpusheshop** [comment]
Ok, I moved forward. Now the script fills usernam and pasword. the usernam and psw are export correctly in the cmd, but in instagram log in page the script writes it with "<>" so from username is <username>. Any suggestion, but thank you very much!!

**Comment by vlntdds** [comment]
Are you writing "<username>" or "username"?

**Comment by anpusheshop** [comment]
It is working finally. Thank you very much...

**Comment by AlainPilon** [comment]
Well, I had to reinstall everything and now I am getting this`no len()` error... What did you do to fix it? My PW and and login are correctly exported.

**Comment by foname** [comment]
Please make sure that you export with correct variable names.
If you are newly pull from master, in your quickstart.py will look like below:

`InstaPy(username=os.getenv('INSTAGRAM_USER'), password=os.getenv('INSTAGRAM_PW'))`

In this case you have to export 'INSTAGRAM_USER' and 'INSTAGRAM_PW'
In order to make sure try to use 'printenv' to check the values.

**Comment by AlainPilon** [comment]
was a typo on my end... I think we can close this now.

**Comment by timgrossmann** [comment]
@AlainPilon Perfect, thank you!
